# Generated by Django 5.2 on 2025-05-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_types', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate Event'), ('anniversary', 'Anniversary'), ('party', 'Party')], default='wedding', max_length=20)),
                ('available_dates', models.JSONField(default=list)),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('photographer', 'Photographer'), ('decorator', 'Decorator'), ('caterer', 'Caterer')], max_length=20)),
                ('location', models.CharField(choices=[('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('khulna', 'Khulna'), ('rajshahi', 'Rajshahi'), ('barishal', 'Barishal'), ('sylhet', 'Sylhet'), ('mymensingh', 'Mymensingh'), ('rangpur', 'Rangpur')], max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price', models.CharField(max_length=50)),
                ('experience', models.PositiveIntegerField()),
                ('short_desc', models.TextField()),
                ('image', models.ImageField(upload_to='service_providers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
