# Generated by Django 5.2 on 2025-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='price',
            field=models.IntegerField(),
        ),
    ]
