# Generated by Django 5.2 on 2025-05-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceprovider_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='events_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='languages',
            field=models.CharField(default='Bangla, English', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='price_unit',
            field=models.CharField(default='per event', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='travel_info',
            field=models.CharField(default='Within city', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='package_features',
            field=models.ManyToManyField(blank=True, related_name='providers', to='services.packagefeature'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='services_offered',
            field=models.ManyToManyField(blank=True, related_name='providers', to='services.service'),
        ),
    ]
